{{- range $user := .Values.users }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dev-{{ $user.port }}
  labels:
    app: java-dev-{{ $user.port }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-dev-{{ $user.port }}
  template:
    metadata:
      labels:
        app: java-dev-{{ $user.port }}
    spec:
      containers:
        - name: java-dev-{{ $user.port }}
          image: {{ $.Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: VNC_PW
              value: {{ $user.password }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 6901
          {{- if $.Values.pv.enable -}}
          volumeMounts:
            - name: home
              mountPath: /home/kasm-user
          {{- end }}
      {{- if $.Values.pv.enable -}}
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home-{{ $user.port }}
      {{- end }}
{{- end }}
