{{- if .Values.pv.enable -}}
{{- range $user := .Values.users }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-{{ $user.port }}
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
{{- end }}
{{- end }}
