apiVersion: v1
data:
  key_id: {{ .Values.awsAccessKeyID | b64enc | quote }}
  access_key: {{ .Values.awsSecretAccessKey | b64enc | quote }}
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
