# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ubuntu-jammy-dind-ingress
#   annotations:
#     nginx.org/rewrites: "serviceName=ubuntu-jammy-dind-0-svc rewrite=/;serviceName=test-svc rewrite=/"
# spec:
#   ingressClassName: nginx
#   # tls:
#   #   - hosts:
#   #       - a916158f02c314491841cc104e5ac94e-813307043.ap-northeast-1.elb.amazonaws.com
#   #     secretName: mytls
#   rules:
#     # - host: sample.training-for-cndt2023.ps.casareal.co.jp
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ubuntu-jammy-dind-0-svc
#                 port:
#                   number: 443
#           - path: /test
#             pathType: Prefix
#             backend:
#               service:
#                 name: test-svc
#                 port:
#                   number: 80

#           # {{- range $index, $user := .Values.users }}
#           #   backend:
#           #     service:
#           #       name: ubuntu-jammy-dind-{{ $index }}-svc
#           #       port:
#           #         number: 443
#           # {{- end}}
