{{- range $user := .Values.users }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-jammy-dind-{{ $user.port }}
  labels:
    app: ubuntu-jammy-dind-{{ $user.port }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-jammy-dind-{{ $user.port }}
  template:
    metadata:
      labels:
        app: ubuntu-jammy-dind-{{ $user.port }}
    spec:
      containers:
        - name: ubuntu-jammy-dind-{{ $user.port }}
          image: kasmweb/ubuntu-jammy-dind:1.14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: VNC_PW
              value: {{ $user.password }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 6901
      #     volumeMounts:
      #       - name: persistent-storage-{{ $user.port }}
      #         mountPath: /mnt/ebs
      # volumes:
      #   - name: persistent-storage-{{ $user.port }}
      #     persistentVolumeClaim:
      #       claimName: ebs-claim-{{ $user.port }}
{{- end }}
