{{- range $user := .Values.users }}
---
apiVersion: v1
kind: Service
metadata:
  name: unityhub-{{ $user.port }}-svc
spec:
  selector:
    app: unityhub-{{ $user.port }}
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 6901
      nodePort: {{ $user.port }} 
  type: NodePort
{{- end }}
